# Generated by Django 3.1.6 on 2021-02-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20210224_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airmarshalllogswithnotes',
            name='response_date',
        ),
        migrations.AddField(
            model_name='airmarshalllogswithnotes',
            name='response_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
