# Generated by Django 3.1.6 on 2021-02-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20210225_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airmarshalllogswithnotes',
            old_name='resolved',
            new_name='investigator_resolved',
        ),
        migrations.AddField(
            model_name='airmarshalllogswithnotes',
            name='assignee_resolved',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='airmarshalllogswithnotes',
            name='response_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
