# Generated by Django 3.1.6 on 2021-02-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20210225_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airmarshalllogswithnotes',
            name='assignee_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
