# Generated by Django 3.1.6 on 2021-02-25 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20210225_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='acknowledge_boolean',
            new_name='for_acknowledged',
        ),
    ]
