# Generated by Django 3.1.6 on 2021-02-17 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentTasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('unseen', 'UNSEEN'), ('backlog', 'BACKLOG'), ('development', 'DEV'), ('finished', 'FINISHED'), ('skipped', 'SKIP')], default='unseen', max_length=12)),
                ('response', models.TextField()),
                ('task_image', models.ImageField(blank=True, upload_to='task_image/')),
                ('etl_ingestion_time', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
