# Generated by Django 3.1.6 on 2021-02-15 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirMarshallResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged', models.BooleanField()),
                ('partner_id', models.CharField(max_length=30)),
                ('airflow_id', models.IntegerField()),
                ('reason', models.CharField(max_length=300)),
                ('issue_id', models.CharField(max_length=75)),
                ('etl_ingestion_time', models.DateTimeField(auto_now=True)),
                ('dag_id', models.CharField(max_length=300)),
                ('task_id', models.CharField(blank=True, max_length=300, null=True)),
                ('support_notes', models.TextField(blank=True, null=True)),
                ('dag_start_datetime', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
